return {
  "ThePrimeagen/refactoring.nvim",
  event = "User AstroFile",
  dependencies = { "lewis6991/async.nvim" },
  opts = {},
  keys = {
    { "<Leader>rb", function() return require("refactoring").extract_func() end, desc = "Extract Function", expr = true },
    { "<Leader>ri", function() return require("refactoring").inline_var() end, desc = "Inline Variable", expr = true },
    {
      "<Leader>rp",
      function() return require("refactoring.debug").print_loc { output_location = "above" } end,
      desc = "Debug: Print Location",
      expr = true,
    },
    {
      "<Leader>rc",
      function() return require("refactoring.debug").cleanup { restore_view = true } end,
      desc = "Debug: Clean Up",
      expr = true,
      remap = true,
    },
    {
      "<Leader>rd",
      function() return require("refactoring.debug").print_var { output_location = "above" } end,
      desc = "Debug: Print Variable",
      expr = true,
      remap = true,
    },
    {
      "<Leader>rbf",
      function() return require("refactoring").extract_func_to_file() end,
      desc = "Extract Function To File",
      expr = true,
    },
    { "<Leader>re", function() return require("refactoring").extract_func() end, mode = "v", desc = "Extract Function", expr = true },
    {
      "<Leader>rf",
      function() return require("refactoring").extract_func_to_file() end,
      mode = "v",
      desc = "Extract Function To File",
      expr = true,
    },
    { "<Leader>rv", function() return require("refactoring").extract_var() end, mode = "v", desc = "Extract Variable", expr = true },
    { "<Leader>ri", function() return require("refactoring").inline_var() end, mode = "v", desc = "Inline Variable", expr = true },
    { "<Leader>rb", function() return require("refactoring").extract_func() end, mode = "v", desc = "Extract Function", expr = true },
    {
      "<Leader>rbf",
      function() return require("refactoring").extract_func_to_file() end,
      mode = "v",
      desc = "Extract Function To File",
      expr = true,
    },
    { "<Leader>rr", function() require("refactoring").select_refactor() end, mode = "v", desc = "Select Refactor" },
    {
      "<Leader>rp",
      function() return require("refactoring.debug").print_exp { output_location = "above" } end,
      mode = "v",
      desc = "Debug: Print Expression",
      expr = true,
    },
    {
      "<Leader>rc",
      function() return require("refactoring.debug").cleanup { restore_view = true } end,
      mode = "v",
      desc = "Debug: Clean Up",
      expr = true,
      remap = true,
    },
    {
      "<Leader>rd",
      function() return require("refactoring.debug").print_var { output_location = "above" } end,
      mode = "v",
      desc = "Debug: Print Variable",
      expr = true,
    },
  },
}
